# Basic branch protection for small teams
# Minimal configuration for protecting main branch
apiVersion: branchprotection.gitea.crossplane.io/v1alpha1
kind: BranchProtection
metadata:
  name: basic-main-protection
  annotations:
    crossplane.io/external-name: "myorg/myapp/main"
spec:
  forProvider:
    repository: "myorg/myapp"
    branch: "main"
    ruleName: "Basic main protection"

    # Require at least one approval
    requiredApprovals: 1

    # Block direct pushes
    enablePush: false

    # Require status checks
    enableStatusCheck: true
    statusCheckContexts:
      - "ci/build"
      - "ci/test"

    # Basic review protection
    blockOnRejectedReviews: true

  providerConfigRef:
    name: default
