# golangci-lint configuration for provider-gitea
# Compatible with golangci-lint v2.3.0

run:
  timeout: 10m
  tests: true
  skip-dirs:
    - build
    - _output
  skip-files:
    - "zz_generated\\..*\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gocyclo:
    min-complexity: 15
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/crossplane-contrib/provider-gitea
  
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  
  lll:
    line-length: 120
  
  misspell:
    locale: US
    ignore-words:
      - crossplane
      - gitea

  revive:
    rules:
      - name: exported
        disabled: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - goconst
    - gocyclo
    - misspell
    - lll
    - revive

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - goconst
    
    # Exclude generated files
    - path: zz_generated\..*\.go
      linters:
        - revive
        - stylecheck
        - goimports
    
    # Allow long lines in generated code
    - path: zz_generated\..*\.go
      linters:
        - lll

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false