//go:build !ignore_autogenerated

/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v2

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchProtection) DeepCopyInto(out *BranchProtection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchProtection.
func (in *BranchProtection) DeepCopy() *BranchProtection {
	if in == nil {
		return nil
	}
	out := new(BranchProtection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BranchProtection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchProtectionAppliedSettings) DeepCopyInto(out *BranchProtectionAppliedSettings) {
	*out = *in
	if in.EnablePush != nil {
		in, out := &in.EnablePush, &out.EnablePush
		*out = new(bool)
		**out = **in
	}
	if in.EnableStatusCheck != nil {
		in, out := &in.EnableStatusCheck, &out.EnableStatusCheck
		*out = new(bool)
		**out = **in
	}
	if in.RequiredStatusChecks != nil {
		in, out := &in.RequiredStatusChecks, &out.RequiredStatusChecks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchProtectionAppliedSettings.
func (in *BranchProtectionAppliedSettings) DeepCopy() *BranchProtectionAppliedSettings {
	if in == nil {
		return nil
	}
	out := new(BranchProtectionAppliedSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchProtectionList) DeepCopyInto(out *BranchProtectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BranchProtection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchProtectionList.
func (in *BranchProtectionList) DeepCopy() *BranchProtectionList {
	if in == nil {
		return nil
	}
	out := new(BranchProtectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BranchProtectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchProtectionObservation) DeepCopyInto(out *BranchProtectionObservation) {
	*out = *in
	if in.RuleName != nil {
		in, out := &in.RuleName, &out.RuleName
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = new(string)
		**out = **in
	}
	if in.AppliedSettings != nil {
		in, out := &in.AppliedSettings, &out.AppliedSettings
		*out = new(BranchProtectionAppliedSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchProtectionObservation.
func (in *BranchProtectionObservation) DeepCopy() *BranchProtectionObservation {
	if in == nil {
		return nil
	}
	out := new(BranchProtectionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchProtectionParameters) DeepCopyInto(out *BranchProtectionParameters) {
	*out = *in
	if in.EnablePush != nil {
		in, out := &in.EnablePush, &out.EnablePush
		*out = new(bool)
		**out = **in
	}
	if in.EnablePushWhitelist != nil {
		in, out := &in.EnablePushWhitelist, &out.EnablePushWhitelist
		*out = new(bool)
		**out = **in
	}
	if in.PushWhitelistUsernames != nil {
		in, out := &in.PushWhitelistUsernames, &out.PushWhitelistUsernames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PushWhitelistTeams != nil {
		in, out := &in.PushWhitelistTeams, &out.PushWhitelistTeams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PushWhitelistDeployKeys != nil {
		in, out := &in.PushWhitelistDeployKeys, &out.PushWhitelistDeployKeys
		*out = new(bool)
		**out = **in
	}
	if in.EnableMergeWhitelist != nil {
		in, out := &in.EnableMergeWhitelist, &out.EnableMergeWhitelist
		*out = new(bool)
		**out = **in
	}
	if in.MergeWhitelistUsernames != nil {
		in, out := &in.MergeWhitelistUsernames, &out.MergeWhitelistUsernames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MergeWhitelistTeams != nil {
		in, out := &in.MergeWhitelistTeams, &out.MergeWhitelistTeams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnableStatusCheck != nil {
		in, out := &in.EnableStatusCheck, &out.EnableStatusCheck
		*out = new(bool)
		**out = **in
	}
	if in.StatusCheckContexts != nil {
		in, out := &in.StatusCheckContexts, &out.StatusCheckContexts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequiredApprovals != nil {
		in, out := &in.RequiredApprovals, &out.RequiredApprovals
		*out = new(int)
		**out = **in
	}
	if in.EnableApprovalsWhitelist != nil {
		in, out := &in.EnableApprovalsWhitelist, &out.EnableApprovalsWhitelist
		*out = new(bool)
		**out = **in
	}
	if in.ApprovalsWhitelistUsernames != nil {
		in, out := &in.ApprovalsWhitelistUsernames, &out.ApprovalsWhitelistUsernames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ApprovalsWhitelistTeams != nil {
		in, out := &in.ApprovalsWhitelistTeams, &out.ApprovalsWhitelistTeams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlockOnRejectedReviews != nil {
		in, out := &in.BlockOnRejectedReviews, &out.BlockOnRejectedReviews
		*out = new(bool)
		**out = **in
	}
	if in.BlockOnOfficialReviewRequests != nil {
		in, out := &in.BlockOnOfficialReviewRequests, &out.BlockOnOfficialReviewRequests
		*out = new(bool)
		**out = **in
	}
	if in.BlockOnOutdatedBranch != nil {
		in, out := &in.BlockOnOutdatedBranch, &out.BlockOnOutdatedBranch
		*out = new(bool)
		**out = **in
	}
	if in.DismissStaleApprovals != nil {
		in, out := &in.DismissStaleApprovals, &out.DismissStaleApprovals
		*out = new(bool)
		**out = **in
	}
	if in.RequireSignedCommits != nil {
		in, out := &in.RequireSignedCommits, &out.RequireSignedCommits
		*out = new(bool)
		**out = **in
	}
	if in.ProtectedFilePatterns != nil {
		in, out := &in.ProtectedFilePatterns, &out.ProtectedFilePatterns
		*out = new(string)
		**out = **in
	}
	if in.UnprotectedFilePatterns != nil {
		in, out := &in.UnprotectedFilePatterns, &out.UnprotectedFilePatterns
		*out = new(string)
		**out = **in
	}
	if in.ConnectionRef != nil {
		in, out := &in.ConnectionRef, &out.ConnectionRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProviderConfigRef != nil {
		in, out := &in.ProviderConfigRef, &out.ProviderConfigRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchProtectionParameters.
func (in *BranchProtectionParameters) DeepCopy() *BranchProtectionParameters {
	if in == nil {
		return nil
	}
	out := new(BranchProtectionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchProtectionSpec) DeepCopyInto(out *BranchProtectionSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchProtectionSpec.
func (in *BranchProtectionSpec) DeepCopy() *BranchProtectionSpec {
	if in == nil {
		return nil
	}
	out := new(BranchProtectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchProtectionStatus) DeepCopyInto(out *BranchProtectionStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchProtectionStatus.
func (in *BranchProtectionStatus) DeepCopy() *BranchProtectionStatus {
	if in == nil {
		return nil
	}
	out := new(BranchProtectionStatus)
	in.DeepCopyInto(out)
	return out
}
