//go:build !ignore_autogenerated

/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamRepository) DeepCopyInto(out *TeamRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamRepository.
func (in *TeamRepository) DeepCopy() *TeamRepository {
	if in == nil {
		return nil
	}
	out := new(TeamRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TeamRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamRepositoryList) DeepCopyInto(out *TeamRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TeamRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamRepositoryList.
func (in *TeamRepositoryList) DeepCopy() *TeamRepositoryList {
	if in == nil {
		return nil
	}
	out := new(TeamRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TeamRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamRepositoryObservation) DeepCopyInto(out *TeamRepositoryObservation) {
	*out = *in
	if in.TeamID != nil {
		in, out := &in.TeamID, &out.TeamID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamRepositoryObservation.
func (in *TeamRepositoryObservation) DeepCopy() *TeamRepositoryObservation {
	if in == nil {
		return nil
	}
	out := new(TeamRepositoryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamRepositoryParameters) DeepCopyInto(out *TeamRepositoryParameters) {
	*out = *in
	if in.TeamID != nil {
		in, out := &in.TeamID, &out.TeamID
		*out = new(int64)
		**out = **in
	}
	if in.ConnectionRef != nil {
		in, out := &in.ConnectionRef, &out.ConnectionRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProviderConfigRef != nil {
		in, out := &in.ProviderConfigRef, &out.ProviderConfigRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamRepositoryParameters.
func (in *TeamRepositoryParameters) DeepCopy() *TeamRepositoryParameters {
	if in == nil {
		return nil
	}
	out := new(TeamRepositoryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamRepositorySpec) DeepCopyInto(out *TeamRepositorySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamRepositorySpec.
func (in *TeamRepositorySpec) DeepCopy() *TeamRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(TeamRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamRepositoryStatus) DeepCopyInto(out *TeamRepositoryStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamRepositoryStatus.
func (in *TeamRepositoryStatus) DeepCopy() *TeamRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(TeamRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}
