# Repository secret for external API integration
# This example creates secrets for third-party service integration
apiVersion: repositorysecret.gitea.crossplane.io/v1alpha1
kind: RepositorySecret
metadata:
  name: slack-webhook-url
  annotations:
    crossplane.io/external-name: "myorg/backend-api/SLACK_WEBHOOK_URL"
spec:
  forProvider:
    repository: "myorg/backend-api"
    secretName: "SLACK_WEBHOOK_URL"

    dataSecretRef:
      name: "slack-integration"
      namespace: "crossplane-system"
      key: "webhook-url"

  providerConfigRef:
    name: default

---
apiVersion: repositorysecret.gitea.crossplane.io/v1alpha1
kind: RepositorySecret
metadata:
  name: aws-access-key
  annotations:
    crossplane.io/external-name: "myorg/backend-api/AWS_ACCESS_KEY_ID"
spec:
  forProvider:
    repository: "myorg/backend-api"
    secretName: "AWS_ACCESS_KEY_ID"

    dataSecretRef:
      name: "aws-credentials"
      namespace: "crossplane-system"
      key: "access-key-id"

  providerConfigRef:
    name: default

---
# Supporting Kubernetes secrets
apiVersion: v1
kind: Secret
metadata:
  name: slack-integration
  namespace: crossplane-system
type: Opaque
data:
  webhook-url: "aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA="

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: crossplane-system
type: Opaque
data:
  access-key-id: "QUtJQUlPU0ZPRE5ON0VYQU1QTEU="
