# Repository secret for Docker registry authentication
# This example creates a secret for container image deployment
apiVersion: repositorysecret.gitea.crossplane.io/v1alpha1
kind: RepositorySecret
metadata:
  name: docker-registry-auth
  annotations:
    crossplane.io/external-name: "example-org/microservice/DOCKER_PASSWORD"
spec:
  forProvider:
    # Repository in owner/name format
    repository: "example-org/microservice"
    
    # Secret name as used in Actions workflows
    secretName: "DOCKER_PASSWORD"
    
    # Reference to Kubernetes secret containing the actual value
    dataSecretRef:
      name: "docker-credentials"
      namespace: "crossplane-system"
      key: "password"
    
  providerConfigRef:
    name: default

---
# Supporting Kubernetes secret
apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: crossplane-system
type: Opaque
data:
  password: "bXlzZWNyZXRwYXNzd29yZA==" # base64 encoded password