# Administrative service accounts for automation
# This example creates service accounts with admin privileges
apiVersion: adminuser.gitea.crossplane.io/v1alpha1
kind: AdminUser
metadata:
  name: ci-service-account
  annotations:
    crossplane.io/external-name: "ci-service"
spec:
  forProvider:
    # Username for the service account
    username: "ci-service"

    # Service account email
    email: "ci-service@company.com"

    # Password stored in Kubernetes secret
    passwordSecretRef:
      name: "ci-service-credentials"
      namespace: "crossplane-system"
      key: "password"

    # Display name
    fullName: "CI/CD Service Account"

    # Admin privileges for service operations
    isAdmin: true

    # Account settings
    isActive: true
    isRestricted: false
    prohibitLogin: false

    # Visibility and limits
    visibility: "private"
    maxRepoCreation: 50

    # Service account description
    description: "Automated service account for CI/CD operations"

  providerConfigRef:
    name: default

---
apiVersion: adminuser.gitea.crossplane.io/v1alpha1
kind: AdminUser
metadata:
  name: backup-service-account
  annotations:
    crossplane.io/external-name: "backup-service"
spec:
  forProvider:
    username: "backup-service"
    email: "backup-service@company.com"

    passwordSecretRef:
      name: "backup-service-credentials"
      namespace: "crossplane-system"
      key: "password"

    fullName: "Backup Service Account"
    isAdmin: true
    isActive: true
    isRestricted: true  # Restricted admin for security
    prohibitLogin: true  # Cannot login interactively

    visibility: "private"
    maxRepoCreation: 0  # Cannot create repos

    description: "Service account for automated backups"

  providerConfigRef:
    name: default

---
# Supporting Kubernetes secrets
apiVersion: v1
kind: Secret
metadata:
  name: ci-service-credentials
  namespace: crossplane-system
type: Opaque
data:
  password: "Q2ktU2VydmljZS1QYXNzd29yZC0yMDI0"  # base64 encoded

---
apiVersion: v1
kind: Secret
metadata:
  name: backup-service-credentials
  namespace: crossplane-system
type: Opaque
data:
  password: "QmFja3VwLVNlcnZpY2UtUGFzc3dvcmQtMjAyNA=="  # base64 encoded
