//go:build !ignore_autogenerated

/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v2

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppliedOrganizationSettings) DeepCopyInto(out *AppliedOrganizationSettings) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Website != nil {
		in, out := &in.Website, &out.Website
		*out = new(string)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppliedOrganizationSettings.
func (in *AppliedOrganizationSettings) DeepCopy() *AppliedOrganizationSettings {
	if in == nil {
		return nil
	}
	out := new(AppliedOrganizationSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationSettings) DeepCopyInto(out *OrganizationSettings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationSettings.
func (in *OrganizationSettings) DeepCopy() *OrganizationSettings {
	if in == nil {
		return nil
	}
	out := new(OrganizationSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrganizationSettings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationSettingsList) DeepCopyInto(out *OrganizationSettingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OrganizationSettings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationSettingsList.
func (in *OrganizationSettingsList) DeepCopy() *OrganizationSettingsList {
	if in == nil {
		return nil
	}
	out := new(OrganizationSettingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrganizationSettingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationSettingsObservation) DeepCopyInto(out *OrganizationSettingsObservation) {
	*out = *in
	if in.OrganizationID != nil {
		in, out := &in.OrganizationID, &out.OrganizationID
		*out = new(int64)
		**out = **in
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.AppliedSettings != nil {
		in, out := &in.AppliedSettings, &out.AppliedSettings
		*out = new(AppliedOrganizationSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationSettingsObservation.
func (in *OrganizationSettingsObservation) DeepCopy() *OrganizationSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(OrganizationSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationSettingsParameters) DeepCopyInto(out *OrganizationSettingsParameters) {
	*out = *in
	if in.DefaultRepoPermission != nil {
		in, out := &in.DefaultRepoPermission, &out.DefaultRepoPermission
		*out = new(string)
		**out = **in
	}
	if in.MembersCanCreateRepos != nil {
		in, out := &in.MembersCanCreateRepos, &out.MembersCanCreateRepos
		*out = new(bool)
		**out = **in
	}
	if in.MembersCanCreatePrivate != nil {
		in, out := &in.MembersCanCreatePrivate, &out.MembersCanCreatePrivate
		*out = new(bool)
		**out = **in
	}
	if in.MembersCanCreateInternal != nil {
		in, out := &in.MembersCanCreateInternal, &out.MembersCanCreateInternal
		*out = new(bool)
		**out = **in
	}
	if in.MembersCanDeleteRepos != nil {
		in, out := &in.MembersCanDeleteRepos, &out.MembersCanDeleteRepos
		*out = new(bool)
		**out = **in
	}
	if in.MembersCanFork != nil {
		in, out := &in.MembersCanFork, &out.MembersCanFork
		*out = new(bool)
		**out = **in
	}
	if in.MembersCanCreatePages != nil {
		in, out := &in.MembersCanCreatePages, &out.MembersCanCreatePages
		*out = new(bool)
		**out = **in
	}
	if in.DefaultRepoVisibility != nil {
		in, out := &in.DefaultRepoVisibility, &out.DefaultRepoVisibility
		*out = new(string)
		**out = **in
	}
	if in.RequireSignedCommits != nil {
		in, out := &in.RequireSignedCommits, &out.RequireSignedCommits
		*out = new(bool)
		**out = **in
	}
	if in.EnableDependencyGraph != nil {
		in, out := &in.EnableDependencyGraph, &out.EnableDependencyGraph
		*out = new(bool)
		**out = **in
	}
	if in.AllowGitHooks != nil {
		in, out := &in.AllowGitHooks, &out.AllowGitHooks
		*out = new(bool)
		**out = **in
	}
	if in.AllowCustomGitHooks != nil {
		in, out := &in.AllowCustomGitHooks, &out.AllowCustomGitHooks
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionRef != nil {
		in, out := &in.ConnectionRef, &out.ConnectionRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProviderConfigRef != nil {
		in, out := &in.ProviderConfigRef, &out.ProviderConfigRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationSettingsParameters.
func (in *OrganizationSettingsParameters) DeepCopy() *OrganizationSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(OrganizationSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationSettingsSpec) DeepCopyInto(out *OrganizationSettingsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationSettingsSpec.
func (in *OrganizationSettingsSpec) DeepCopy() *OrganizationSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(OrganizationSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationSettingsStatus) DeepCopyInto(out *OrganizationSettingsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationSettingsStatus.
func (in *OrganizationSettingsStatus) DeepCopy() *OrganizationSettingsStatus {
	if in == nil {
		return nil
	}
	out := new(OrganizationSettingsStatus)
	in.DeepCopyInto(out)
	return out
}
