apiVersion: organizationsecret.gitea.crossplane.io/v1alpha1
kind: OrganizationSecret
metadata:
  name: example-secret-from-k8s
  annotations:
    crossplane.io/external-name: DATABASE_URL
spec:
  forProvider:
    organization: my-example-org
    secretName: DATABASE_URL
    dataFrom:
      secretKeyRef:
        name: app-secrets
        namespace: default
        key: database-url
  providerConfigRef:
    name: default
