apiVersion: organizationsecret.gitea.crossplane.io/v1alpha1
kind: OrganizationSecret
metadata:
  name: example-direct-secret
  annotations:
    crossplane.io/external-name: DEPLOY_TOKEN
spec:
  forProvider:
    organization: my-example-org
    secretName: DEPLOY_TOKEN
    data: "github_pat_11ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
  providerConfigRef:
    name: default
