apiVersion: organizationsecret.gitea.m.crossplane.io/v2
kind: OrganizationSecret
metadata:
  name: example-secret-from-k8s
  namespace: default
  annotations:
    crossplane.io/external-name: DATABASE_URL
spec:
  forProvider:
    organization: my-example-org
    secretName: DATABASE_URL
    valueSecretRef:
      namespace: default
      name: app-secrets
      key: database-url
  providerConfigRef:
    name: default
