apiVersion: user.gitea.crossplane.io/v1alpha1
kind: User
metadata:
  name: example-user
  annotations:
    crossplane.io/external-name: johndoe
spec:
  forProvider:
    username: johndoe
    email: john.doe@example.com
    password: "SecurePassword123!"
    fullName: "John Doe"
    sendNotify: false
    mustChangePassword: true
    restricted: false
    visibility: public
  providerConfigRef:
    name: default
