apiVersion: user.gitea.m.crossplane.io/v2
kind: User
metadata:
  name: example-user
  namespace: default
  annotations:
    crossplane.io/external-name: johndoe
spec:
  forProvider:
    username: johndoe
    email: john.doe@example.com
    passwordSecretRef:
      namespace: default
      name: example-user-password
      key: password
    fullName: "John Doe"
    sendNotify: false
    mustChangePassword: true
    restricted: false
    visibility: public
  providerConfigRef:
    name: default

---
# Supporting Kubernetes secret holding the user password
apiVersion: v1
kind: Secret
metadata:
  name: example-user-password
  namespace: default
type: Opaque
data:
  # base64-encoded password
  password: "U2VjdXJlUGFzc3dvcmQxMjMh"
