apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gitea
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/crossplane-contrib/provider-gitea
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A Crossplane provider for managing Gitea repositories, organizations, users, and related resources.
    meta.crossplane.io/readme: |
      This provider enables declarative management of Gitea instances through Kubernetes custom resources. 
      It supports managing repositories, organizations, users, webhooks, deploy keys, and access tokens 
      using Crossplane's managed resource lifecycle.

      ## Features
      - Repository Management: Create and manage Git repositories
      - Organization Management: Manage organizations and their settings  
      - User Management: User account management and configuration
      - Webhook Management: Configure repository and organization webhooks
      - Deploy Key Management: Manage SSH deploy keys for repositories
      - Access Token Management: Handle personal and organization access tokens

      ## Getting Started
      1. Install the provider
      2. Create a ProviderConfig with your Gitea instance details
      3. Create managed resources for repositories, organizations, etc.

      See the documentation for detailed usage examples.
spec:
  crossplane:
    version: ">=v1.20.0-0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/function-go-templating
      version: ">=v0.4.0"