apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gitea
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/crossplane-contrib/provider-gitea
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A comprehensive Crossplane provider for managing Gitea with enterprise security, CI/CD integration, administrative capabilities, and secure TLS certificate handling for internal deployments.
    meta.crossplane.io/readme: |
      This provider enables declarative management of Gitea instances through Kubernetes custom resources with enterprise-grade features.
      It supports repository management, organization control, user administration, security enforcement, CI/CD integration, and complete automation workflows.

      ## Core Features
      - **Repository Management**: Full lifecycle management of Git repositories
      - **Organization Management**: Organizations, settings, and membership control
      - **User Administration**: Administrative user management with privilege controls
      - **Webhook Management**: Repository and organization webhook configurations

      ## Security Features (NEW)
      - **Branch Protection**: Enterprise-grade branch protection with approval workflows
      - **SSH Key Management**: User and repository SSH key lifecycle management
      - **Access Token Management**: Scoped API token management with security controls
      - **Repository Secrets**: Secure CI/CD secret management with Kubernetes integration
      - **Organization Membership**: Team membership with role-based access control

      ## CI/CD Integration (NEW)
      - **Actions Workflows**: Declarative CI/CD pipeline management
      - **Self-hosted Runners**: Multi-scope runner management (repository, organization, system)
      - **Complete CI/CD Automation**: End-to-end DevOps workflow orchestration

      ## Administrative Features (NEW)
      - **Administrative Users**: Service account and admin user lifecycle management
      - **Enterprise Security**: Comprehensive security policy enforcement
      - **Multi-tenant Support**: Organization and user isolation with proper access controls

      ## Getting Started
      1. Install the provider: `kubectl apply -f package/`
      2. Create a ProviderConfig with your Gitea credentials
      3. Apply example manifests for complete enterprise setup
      4. Use CI/CD integration for automated DevOps workflows

      ## Example Enterprise Setup
      See `examples/enterprise-complete-setup.yaml` for a comprehensive enterprise configuration including:
      - Administrative users and service accounts
      - Branch protection and security policies
      - CI/CD runners and workflow automation
      - Complete security and compliance setup

      Perfect for organizations requiring enterprise-grade Git management with integrated DevOps automation.

      ## V2 Features (NEW)
      - **Namespaced Resources**: Repository and other resources can now be scoped to namespaces
      - **Enhanced Multi-tenancy**: Namespace-scoped ProviderConfig support
      - **Rich Observability**: Extended status fields for better monitoring and debugging
      - **Modern Architecture**: Built with kubebuilder patterns for better maintainability
spec:
  crossplane:
    version: ">=v2.0.0-0"
