apiVersion: deploykey.gitea.m.crossplane.io/v2
kind: DeployKey
metadata: {name: uptest-deploykey, namespace: provider-gitea-e2e, annotations: {meta.upbound.io/example-id: deploykey/v2/deploykey}}
spec:
  forProvider:
    owner: e2e-user
    repository: uptest-repo
    title: uptest-deploykey
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIuptestdeploykey uptest@e2e"
    readOnly: true
  providerConfigRef: {name: e2e, kind: ProviderConfig}
