apiVersion: pullrequest.gitea.m.crossplane.io/v2
kind: PullRequest
metadata: {name: uptest-pr, namespace: provider-gitea-e2e, annotations: {meta.upbound.io/example-id: pullrequest/v2/pullrequest}}
spec:
  forProvider:
    owner: e2e-user
    repository: uptest-repo
    title: uptest pr
    head: feature
    base: main
  providerConfigRef: {name: e2e, kind: ProviderConfig}
