apiVersion: gitea.m.crossplane.io/v1beta1
kind: RepositorySecret
metadata: {name: uptest-reposecret, namespace: provider-gitea-e2e, annotations: {meta.upbound.io/example-id: repositorysecret/v2/repositorysecret}}
spec:
  forProvider:
    repository: gitea_admin/uptest-repo
    secretName: UPTEST_SECRET
    valueSecretRef: {namespace: provider-gitea-e2e, name: uptest-secret-value, key: value}
  providerConfigRef: {name: e2e, kind: ProviderConfig}
