apiVersion: gitea.m.crossplane.io/v1beta1
kind: RepositoryKey
metadata: {name: uptest-repokey, namespace: provider-gitea-e2e, annotations: {meta.upbound.io/example-id: repositorykey/v2/repositorykey}}
spec:
  forProvider: {repository: gitea_admin/uptest-repo, title: uptest-repokey, key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHvaouhW5kE9t2BXWiwbAPcCWCQWMgtlXQBTTylXo5sa uptest-repokey@e2e"}
  providerConfigRef: {name: e2e, kind: ProviderConfig}
